import type { AnalysisReport, Finding, Severity } from '../types/index.js';

export function generateMarkdownReport(report: AnalysisReport): string {
  const lines: string[] = [];

  lines.push(`# ⚡ dotnet-perf-audit Report`);
  lines.push('');
  lines.push(`| Property | Value |`);
  lines.push(`|----------|-------|`);
  lines.push(`| **Project** | ${report.project.name} |`);
  lines.push(`| **Framework** | .NET ${report.project.dotnetVersion} |`);
  lines.push(`| **Files Analyzed** | ${report.summary.filesAnalyzed} |`);
  lines.push(`| **Health Score** | ${scoreEmoji(report.summary.score)} **${report.summary.score}/100** |`);
  lines.push(`| **Duration** | ${report.duration.toFixed(1)}s |`);
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| 🔴 Critical | ${report.summary.critical} |`);
  lines.push(`| 🟡 Warning | ${report.summary.warning} |`);
  lines.push(`| 🔵 Suggestion | ${report.summary.suggestion} |`);
  lines.push(`| 🟢 Good | ${report.summary.good} |`);
  lines.push('');

  const grouped = groupBySeverity(report.findings);

  if (grouped.critical.length > 0) {
    lines.push('## 🔴 Critical Issues');
    lines.push('');
    for (const f of grouped.critical) {
      lines.push(...renderFinding(f));
    }
  }

  if (grouped.warning.length > 0) {
    lines.push('## 🟡 Warnings');
    lines.push('');
    for (const f of grouped.warning) {
      lines.push(...renderFinding(f));
    }
  }

  if (grouped.suggestion.length > 0) {
    lines.push('## 🔵 Suggestions');
    lines.push('');
    for (const f of grouped.suggestion) {
      lines.push(...renderFinding(f));
    }
  }

  if (grouped.good.length > 0) {
    lines.push('## 🟢 Good Patterns');
    lines.push('');
    for (const f of grouped.good) {
      lines.push(`- ✅ **${f.title}** — ${f.description}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by [dotnet-perf-audit](https://github.com/dotnet-perf-audit) at ${report.timestamp}*`);

  return lines.join('\n');
}

function renderFinding(finding: Finding): string[] {
  const lines: string[] = [];
  const location = finding.line ? `${finding.file}:${finding.line}` : finding.file;

  lines.push(`<details>`);
  lines.push(`<summary><strong>${finding.title}</strong> — <code>${location}</code></summary>`);
  lines.push('');
  lines.push(finding.description);
  lines.push('');

  if (finding.codeSnippet) {
    lines.push('**Problem:**');
    lines.push('```csharp');
    lines.push(finding.codeSnippet);
    lines.push('```');
    lines.push('');
  }

  if (finding.fix) {
    lines.push('**Fix:**');
    lines.push('```csharp');
    lines.push(finding.fix);
    lines.push('```');
    lines.push('');
  }

  if (finding.source) {
    lines.push(`> 📚 Source: *${finding.source}*`);
    lines.push('');
  }

  lines.push('</details>');
  lines.push('');

  return lines;
}

function scoreEmoji(score: number): string {
  if (score >= 90) return '🏆';
  if (score >= 75) return '👍';
  if (score >= 50) return '⚠️';
  return '🔴';
}

function groupBySeverity(findings: Finding[]) {
  return {
    critical: findings.filter((f) => f.severity === 'critical'),
    warning: findings.filter((f) => f.severity === 'warning'),
    suggestion: findings.filter((f) => f.severity === 'suggestion'),
    good: findings.filter((f) => f.severity === 'good'),
  };
}
